version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'franchises'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '13306:3306'
    volumes:
      - ./src/test/resources/db/db_initial.sql:/docker-entrypoint-initdb.d/db_initial.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080