version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'franchises'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources/db/db_initial.sql:/docker-entrypoint-initdb.d/db_initial.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8082:8080'

  franquicias-app:
    container_name: franquicias-app
    depends_on:
      - db
    image: pee-java_app:1.0.0
    restart: always
    build: .
    ports:
      - '8090:8090'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: '3306'
      DATABASE_NAME: 'franchises'
      DATABASE_USER: 'mysqluser'
      DATABASE_PASSWORD: 'secret'